(TeX-add-style-hook
 "chapter9"
 (lambda ()
   (LaTeX-add-labels
    "fig:128"
    "fig:129"
    "fig:130"
    "fig:131"
    "fig:132"
    "fig:133"
    "fig:134"
    "fig:135"
    "fig:136"
    "fig:137"
    "fig:138"
    "fig:139"
    "fig:140"
    "fig:141"
    "fig:142"
    "fig:143"
    "fig:144")
   (LaTeX-add-environments
    '("verse" LaTeX-env-args ["argument"] 0))
   (LaTeX-add-index-entries
    "волна!прибойная"
    "дрейф!вынужденный"
    "парус!шторомовой"
    "дрейф"
    "якорь!плавучий"
    "шторм!убегание"
    "узкости"
    "жвака-галс"
    "якорь!постановка!<<гусёк>>"
    "глаголь-гак"
    "шквал"
    "ветер!шквал"
    "шквал!белый"
    "ветер!шквал!белый"))
 :latex)

