(TeX-add-style-hook
 "chapter7"
 (lambda ()
   (setq TeX-command-extra-options
         "-shell-escape")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (LaTeX-add-labels
    "chap:7"
    "sec:7-1"
    "fig:87"
    "fig:88"
    "eq:56"
    "fig:89"
    "eq:58"
    "sec:7-2"
    "fig:90"
    "fig:91"
    "fig:92"
    "eq:59"
    "cruiserfix"
    "eq:60"
    "eq:61"
    "eq:62"
    "eq:63"
    "eq:64"
    "eq:65-1"
    "eq:65-2"
    "eq:66"
    "eq:67"
    "eq:68"
    "eq:69"
    "sec:7-3"
    "fig:93"
    "sec:7-4"
    "fig:94"
    "fig:95"
    "eq:70"
    "eq:71"
    "fig:96"
    "sec:7-5"
    "fig:97"
    "fig:98"
    "fig:99"
    "fig:100"
    "fig:101"
    "fig:102"
    "fig:103"
    "eq:72"
    "eq:73"
    "fig:104"
    "fig:105"
    "eq:74"
    "eq:75"
    "fig:106"
    "fig:107"
    "eq:76"
    "eq:77"
    "fig:108")
   (LaTeX-add-index-entries
    "высота светила"
    "азимут!круговой"
    "азимут!полукруговой"
    "координаты!горизонтальные"
    "видимое место"
    "географическое место"
    "склонение"
    "гринвичский часовой угол"
    "местный часовой угол"
    "точка весны"
    "точка Овна"
    "звёздный угол"
    "звёздное дополнение"
    "прямое восхождение"
    "звёздное время"
    "полуденная точка"
    "эклиптика"
    "фаза Луны"
    "возраст Луны"
    "сизигия"
    "солнечное время"
    "время!местное"
    "время!меридианное"
    "полуденная линия"
    "сутки"
    "солнечные часы!экваториальные"
    "солнечные часы!горизонтальные"
    "время!среднее"
    "время!среднее!местное"
    "время!среднее!меридианное"
    "время!уравнение"
    "время!всемирное"
    "время!гринвичское"
    "ход часов"
    "ход часов!суточный"
    "время!формула хранения"
    "сумерки!навигационные утренние"
    "сумерки!гражданские"
    "сумерки!навигационные вечерние"
    "круг равных высот"
    "высотные линии положения"))
 :latex)

