(TeX-add-style-hook
 "chapter5"
 (lambda ()
   (setq TeX-command-extra-options
         "-shell-escape")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (LaTeX-add-labels
    "fig:54"
    "fig:55"
    "fig:56"
    "fig:57"
    "fig:58"
    "sec:maps")
   (LaTeX-add-index-entries
    "лоция морская"
    "гавань"
    "бухта"
    "порт"
    "port"
    "рейд"
    "roadstead"
    "harbour"
    "бассейн"
    "dock basin"
    "аванпорт"
    "outer harbour"
    "дамба"
    "dam"
    "мол"
    "mole"
    "волнолом"
    "breakwater"
    "причал"
    "pier"
    "berth"
    "пал"
    "pawl"
    "bit"
    "фарватер"
    "fairway"
    "канал"
    "canal"
    "bay"
    "фьорд"
    "fiord"
    "мель"
    "flat"
    "ground"
    "отмель"
    "shoal"
    "риф"
    "reef"
    "банка"
    "bank"
    "бар"
    "bar of river"
    "глина"
    "clay"
    "ил"
    "mud"
    "slime"
    "ooze"
    "песок"
    "гравий"
    "хрящ"
    "sand"
    "gravel"
    "плита"
    "грунт!твёрдый"
    "hard ground"
    "веха"
    "spar buoy"
    "буй"
    "buoy"
    "бакен"
    "beacon"
    "маяк"
    "light house"
    "маяк!плавучий"
    "lightship"
    "створ"
    "leading line"
    "ограждение!плавучее"
    "ограждение!береговое"
    "опасности!морские!постоянные"
    "латеральная система"
    "кардинальная система"
    "ограждение!штатное"
    "ограждение!летнее"
    "ограждение!зимнее"
    "маяк!береговой"
    "маяк!морской"
    "радиопеленгаторные станции"
    "радиомаяк"
    "лоцманская станция"
    "спасательная станция"
    "карты!морские"
    "карты!генеральные"
    "карты!путевые"
    "карты!частные"
    "карты!планы"
    "планы"
    "карты!глубины"
    "карты!линия опасности"
    "карты!предостерегательная изобата"
    "магнитное склонение"
    "карты!корректура"))
 :latex)

