(TeX-add-style-hook
 "chapter8"
 (lambda ()
   (setq TeX-command-extra-options
         "-shell-escape")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "path")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "url")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "nolinkurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperbaseurl")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperimage")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "hyperref")
   (add-to-list 'LaTeX-verbatim-macros-with-braces-local "href")
   (add-to-list 'LaTeX-verbatim-macros-with-delims-local "path")
   (TeX-run-style-hooks
    "chapter8-a")
   (LaTeX-add-labels
    "fig:109"
    "fig:110"
    "fig:111"
    "fig:stratus"
    "fig:stratocumulus-opacus"
    "fig:nimbostratus"
    "fig:fractostratus"
    "fig:112"
    "fig:113"
    "fig:114"
    "fig:altostratus-translucidus"
    "fig:115"
    "fig:cirrocumulus"
    "fig:cirrostratus"
    "tab:5"
    "fig:116"
    "tab:6"
    "tab:7"
    "fig:117"
    "fig:118"
    "fig:119"
    "fig:120"
    "fig:121"
    "fig:122"
    "fig:123"
    "fig:meteo_map"
    "fig:124"
    "fig:125"
    "fig:126"
    "fig:127")
   (LaTeX-add-environments
    '("verse" LaTeX-env-args ["argument"] 0))
   (LaTeX-add-index-entries
    "барометр!анероид"
    "термометр-атташе"
    "барограф"
    "барограмма"
    "барометрическая тенденция"
    "барическая тенденция"
    "циклон"
    "барический минимум"
    "антициклон"
    "барический максимум"
    "температура воздуха"
    "температура воздуха!амплитуда суточная"
    "влажность воздуха"
    "влажность воздуха!абсолютная"
    "влажность воздуха!относительная"
    "осадки!атмосферные"
    "туман"
    "сухая мгла"
    "смог"
    "ветер"
    "анемометр"
    "ветер!шквал"
    "шквал"
    "смерч"
    "ветер!смерч"
    "ветер!смерч!хорошей погоды"
    "антипассат"
    "ветер!антипассат"
    "пассат"
    "ветер!пассат"
    "сила!Кориолиса"
    "конские широты"
    "бравые весты"
    "гремящие сороковые"
    "ревущие шестидесятые"
    "ветер!господствующий"
    "ветер!местный"
    "бриз"
    "фен"
    "бора"
    "бакинский норд"
    "сирокко"
    "роза ветров"
    "воздушные массы"
    "воздух!арктический"
    "воздух!морской арктический"
    "воздух!континентальный арктический"
    "воздух!полярный"
    "воздух!умеренный"
    "воздух!тропический"
    "воздух!экваториальный"
    "воздушная~масса!холодная"
    "воздушная~масса!тёплая"
    "воздушная~масса!местная"
    "фронт!атмосферный"
    "фронт!тёплый"
    "фронт!холодный!второго~рода"
    "фронт!холодный!первого~рода"
    "фронт!окклюзии"
    "карты!погоды"
    "карты!синоптические"
    "волнение"
    "фронт~волны"
    "волновой~луч"
    "течение!морское"
    "течение!постоянное!Гольфстрим"
    "течение!постоянное!Куросиво"
    "прилив"
    "отлив"
    "прилив!полная~вода"
    "отлив!малая~вода"
    "прилив!величина"))
 :latex)

